version: '2.1'

services:
  mongo:
    image: mongo
    #build: .
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - /var/lib/yandex-dialogs-whatis:/data/db
    ports:
       - 27018:27017

  yandex-dialogs-whatis:
    image: popstas/yandex-dialogs-whatis:v3.7.0
    # build: .
    environment:
      NODE_ENV: production
    volumes:
      - $PWD/src/config.js:/app/src/config.js
    ports:
      - 2756:3002
    restart: always
